# Generated by Django 4.2.3 on 2023-07-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="hashed_url",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
